server:
  port: 8081
  servlet:
    context-path: /demo

logging:
  config: classpath:\\config\\logging-config.xml

spring:
#  mvc:
#    static-path-pattern: /res/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.31:3306/ssm?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&autoReconnect=true&failOverReadOnly=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 257098

    druid:
      # 连接池配置
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 连接等待超时时间
      max-wait: 30000
      # 配置检测可以关闭的空闲连接间隔时间
      time-between-eviction-runs-millis: 60000
      # 配置连接在池中的最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: select '1' from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters, 去掉后监控界面sql无法统计, 'wall'用于防火墙
      filters: stat,wall
      # Spring监控AOP切入点，如x.y.z.service.*,配置多个英文逗号分隔
      aop-patterns: com.rick.bootdemo.servie.*

      # WebStatFilter配置
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      # StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: true
        # 需要账号密码才能访问控制台
        login-username: Rick
        login-password: 257098
        # IP白名单
        # allow: 127.0.0.1
        #　IP黑名单（共同存在时，deny优先于allow）
        # deny: 192.168.1.218

      # 配置StatFilter
      filter:
        stat:
          log-slow-sql: true
          enabled: true
#          设置慢查询事件限制
          slow-sql-millis: 1000
        wall:
          enabled: true
          config:
            drop-table-allow: false

  mvc:
#    static-path-pattern: /res/**
    converters:
      preferred-json-mapper: gson

  gson:
    date-format: yyyy-MM-dd HH:mm:ss

  servlet:
    multipart:
      enabled: true
      max-file-size: 1024MB
      max-request-size: 10240MB



mybatis:
  # config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
#  可以不写全局配置文件，所有全局配置文件的配置都放在configuration配置项中
  configuration:
    map-underscore-to-camel-case: true


my-profile:
  name: Rick
  email: Kay_Rick@outlook.com

person:
  username: Rick
  age: 21
  salary: 30000

file:
  downloadpath: D:\\Server\\download\\bootdemo\\
  uploadpath: D:\\Server\\upload\\bootdemo\\